### ISSUE TITLE
Question about HTTPWorker

### ISSUE THREAD

**Issue by heatherKoo07** [Bogdanp/web-app-from-scratch#6]
Hello, first I appreciate your incredibly great tutorial series.
I'm currently following part2 and have a quick question about HTTPWorker.

Why do you set the HTTPWorker as daemonic thread when you use join in the main thread?

Here's the HTTPWorker class constructor
```
class HTTPWorker(Thread):
    def __init__(self, connection_queue: Queue) -> None:
        super().__init__(daemon=True)
```
The worker is a daemon thread because of `daemon=True` option.
In the `serve_forever` function of HTTPServer class,
```
for worker in workers:
    worker.join(timeout=30)
```
The main thread is waiting until the child workers are finished.
In my understanding, daemonic thread means main thread won't care if children are automatically killed when it's finished.
So I was curious if there's any reason for setting daemon=True in HTTPWorker.

Thank you

**Comment by Bogdanp** [comment]
Thanks for the kind words! It's been a long time since I wrote that code, so I don't remember exactly what I was thinking. I think you're right and strictly speaking, daemonizing the thread isn't necessary, but it's handy if you need to interrupt the process before the threads can be stopped, for example.

**Comment by heatherKoo07** [comment]
I see. Thanks so much for your response!
Btw, I'm a big fan of dramatiq too! Your work is amazing.

**Comment by Bogdanp** [comment]
You're too kind! I'm going to go ahead and close this now, but feel free to open new issues if you have any other questions.
